version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./microservices/auth-service/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    # volumes:
    #   - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
      - JWT_SECRET=admin
    networks:
      - demo_microservice

  user-service:
    build:
      context: .
      dockerfile: ./microservices/user-service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - rabbitmq
      - auth-service
    # volumes:
    #   - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - JWT_SECRET=admin
      - AUTH_SERVICE_URL=http://auth-service:5000
    networks:
      - demo_microservice

  product-service:
    build:
      context: .
      dockerfile: ./microservices/product-service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - rabbitmq
      - auth-service
      - user-service
    # volumes:
    #   - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
      - AUTH_SERVICE_URL=http://auth-service:5000
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672
    networks:
      - demo_microservice

  shipping-service:
    build:
      context: .
      dockerfile: ./microservices/shipping-service/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - postgres
      - rabbitmq
      - user-service
      - product-service

    # volumes:
    #   - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672

    restart: on-failure

    networks:
      - demo_microservice

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - demo_microservice

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"  # RabbitMQ UI
      - "5672:5672"    # RabbitMQ AMQP
    networks:
      - demo_microservice

volumes:
  postgres-data:  # Persistent storage for PostgreSQL
    driver: local

networks:
  demo_microservice:
    driver: bridge
