version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
    networks:
      - demo_microservice

  user-service:
    build: ./microservices/user-service
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    volumes:
      - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
    networks:
      - demo_microservice

  product-service:
    build: ./microservices/product-service
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
    networks:
      - demo_microservice

  shipping-service:
    build: ./microservices/shipping-service
    ports:
      - "5004:5004"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./shared:/app/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce
      - RABBITMQ_HOST=rabbitmq
    networks:
      - demo_microservice

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - demo_microservice

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"  # RabbitMQ UI
      - "5672:5672"    # RabbitMQ AMQP
    networks:
      - demo_microservice

volumes:
  postgres-data:  # Persistent storage for PostgreSQL
    driver: local

networks:
  demo_microservice:
    driver: bridge
